spring:
  application:
    name: sigin

  datasource:
    url: jdbc:postgresql://localhost:5432/sigin
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true