CREATE TABLE canais_venda (
    id BIGSERIAL PRIMARY KEY,

    nome VARCHAR(80) NOT NULL UNIQUE,

    descricao VARCHAR(255),

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);